version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI = mongodb://mongo:27017/factoryDB
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
